let submit = document.getElementById('mysubmit');
const quotes = [
    "So many books, so little time. - Frank Zappa",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "So many books, so little time. - Frank Zappa",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "So many books, so little time. - Frank Zappa",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "Everything you can imagine is real. - Pablo Picasso",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "So many books, so little time. - Frank Zappa",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "Everything you can imagine is real. - Pablo Picasso",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Not all those who wander are lost. - J.R.R. Tolkien",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison"
];
submit.onclick = function(){
    let rand = Math.floor(Math.random()*101);
    let quats = document.getElementById("quotes");
    quats.textContent = (`"${quotes.at(rand) }"`);
}